'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import { useTheme } from '@emotion/react'

export default function Home() {
  const theme = useTheme()
  console.log(theme)

  return (
    <>
      <Head>
        <title>GuangHui's E-commerce</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/vercel.svg' /> */}
        <link
          rel='icon'
          href='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏪</text></svg>'
        />
      </Head>
      <Button variant='contained'>Hello world</Button>
    </>
  )
}
